# Copyright (c) 2014, Salesforce.com, Inc.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# - Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
# - Neither the name of Salesforce.com nor the names of its contributors
#   may be used to endorse or promote products derived from this
#   software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import fnmatch
import loom
import loom.store
import parsable
parsable = parsable.Parsable()

DOC = os.path.join(loom.ROOT, 'doc')
TRANSFORMS = {}
COLORS = {
    None: 'pink',
    'test': 'cyan',
}
WEIGHTS = {
    None: 1.0,
    'test': 0.1,
}


def transform(**kwargs):

    def decorator(fun):
        loom.documented.TRANSFORMS[fun] = dict(kwargs)
        return fun

    return decorator


def import_all_loom_modules():
    for root, dirnames, filenames in os.walk(os.path.join(loom.ROOT, 'loom')):
        for filename in fnmatch.filter(filenames, '*.py'):
            path = os.path.relpath(os.path.join(root, filename), loom.ROOT)
            module_name = path.replace('/', '.')[:-len('.py')]
            __import__(module_name)


@parsable.command
def make_dataflow(test=False, filenames=True):
    '''
    Make $LOOM/doc/dataflow.dot
    '''
    import_all_loom_modules()
    transforms = loom.documented.TRANSFORMS
    assert transforms, transforms

    if not test:
        transforms = {
            fun: props
            for fun, props in transforms.iteritems()
            if props.get('role') != 'test'
        }

    datas = {}
    paths = loom.store.get_paths('dataset')
    root = paths['root']
    for props in transforms.itervalues():
        for key in props.get('inputs', []) + props.get('outputs', []):
            name = key.replace('.', '_')
            if filenames and key != 'seed':
                path = os.path.relpath(loom.store.get_path(paths, key), root)
                datas[name] = (
                    '<<FONT POINT-SIZE="18">{}</FONT><BR/>{}>'.format(
                        key,
                        os.path.basename(path)))
            else:
                datas[name] = '<<FONT POINT-SIZE="18">{}</FONT>>'.format(key)

    with open(os.path.join(DOC, 'dataflow.dot'), 'w') as f:
        o = lambda line: f.write(line + '\n')

        o('// this file was generated by {}'.format(__file__))
        o('digraph G {')
        o('  overlap=false;')
        o('')
        o('  // data')
        o('  {')
        o('    node [shape=Mrecord];')
        for name, label in datas.iteritems():
            o('    {} [label={}];'.format(name, label))
        o('  }')
        o('')
        o('  // transforms')
        o('  {')
        o('    node [shape=box, style=filled];')
        o('')
        for fun, props in transforms.iteritems():
            color = COLORS[props.get('role')]
            label = '<{}.<BR/><FONT POINT-SIZE="18">{}</FONT>>'.format(
                fun.__module__,
                fun.__name__)
            name = fun.__name__
            o('    {} [label={}, fillcolor={}];'.format(name, label, color))
        o('')
        for fun, props in transforms.iteritems():
            name = fun.__name__
            weight = WEIGHTS[props.get('role')]
            for data in props.get('inputs', []):
                data = data.replace('.', '_')
                o('    {} -> {} [weight={}];'.format(data, name, weight))
            for data in props.get('outputs', []):
                data = data.replace('.', '_')
                o('    {} -> {} [weight={}];'.format(name, data, weight))
        o('  }')
        o('}')


if __name__ == '__main__':
    parsable.dispatch()
